/* Läsning — reading UI. Reads window.READING_DATA from reading-data.js
   (generated by tools/build-reading-site.js). */

(function () {
  'use strict';

  const data = window.READING_DATA;
  const listEl = document.getElementById('articleList');
  const viewEl = document.getElementById('articleView');

  if (!data || !Array.isArray(data.articles)) {
    listEl.innerHTML =
      '<p class="listEmpty">⚠️ 找不到 reading-data.js — 请先运行 <code>node tools/build-reading-site.js</code>。</p>';
    return;
  }

  const articles = data.articles;
  document.getElementById('readingUpdated').textContent =
    `数据更新于 ${data.generatedAt} · 共 ${articles.length} 篇`;

  // ---------- markdown → HTML (headings, lists, bold, code, hr, paragraphs) ----------

  function escapeHtml(s) {
    return String(s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  function inline(s) {
    let t = escapeHtml(s);
    t = t.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_m, slug, label) => {
      const visible = label || slug;
      return `<a href="../#note=${encodeURIComponent(slug)}" target="_blank" rel="noopener">${escapeHtml(visible)}</a>`;
    });
    t = t.replace(/`([^`]+)`/g, '<code>$1</code>');
    t = t.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    return t;
  }

  // Tag each rendered block so we can show/hide the Chinese-translation section.
  // Convention in scenario files: a heading containing "翻译" starts the 🇨🇳 zone,
  // the next same-or-higher-level heading ends it.
  function mdToHtml(md) {
    const lines = md.split(/\r?\n/);
    const out = [];
    let i = 0;
    let inList = false;
    let zhZone = false;
    function closeList() { if (inList) { out.push('</ul>'); inList = false; } }
    const z = () => (zhZone ? ' data-zh="1"' : '');
    while (i < lines.length) {
      const line = lines[i];
      const fence = line.match(/^```(.*)$/);
      if (fence) {
        closeList();
        const buf = [];
        i += 1;
        while (i < lines.length && !/^```/.test(lines[i])) { buf.push(lines[i]); i += 1; }
        out.push(`<pre${z()}><code>` + escapeHtml(buf.join('\n')) + '</code></pre>');
        i += 1;
        continue;
      }
      if (/^\s*(---|\*\*\*|___)\s*$/.test(line)) {
        closeList();
        out.push(`<hr${z()} />`);
        i += 1; continue;
      }
      const h = line.match(/^(#{1,6})\s+(.+)$/);
      if (h) {
        closeList();
        const level = Math.min(4, h[1].length);
        const text = h[2].trim();
        zhZone = /翻译|译文|中文/.test(text);
        out.push(`<h${level}${z()}>${inline(text)}</h${level}>`);
        i += 1; continue;
      }
      const li = line.match(/^\s*[-*]\s+(.+)$/);
      if (li) {
        if (!inList) { out.push(`<ul${z()}>`); inList = true; }
        out.push('<li>' + inline(li[1]) + '</li>');
        i += 1; continue;
      }
      if (line.trim() === '') { closeList(); i += 1; continue; }
      closeList();
      out.push(`<p${z()}>` + inline(line) + '</p>');
      i += 1;
    }
    closeList();
    return out.join('\n');
  }

  // ---------- list rendering ----------

  const KIND_BADGE = {
    scenario: 'scenario', paste: 'paste', adjsubst: 'adjsubst', other: 'other',
  };

  let activeKind = 'all';
  let query = '';
  let currentSlug = null;

  function filtered() {
    return articles.filter((a) => {
      if (activeKind !== 'all' && a.kind !== activeKind) return false;
      if (query && !a.searchText.includes(query)) return false;
      return true;
    });
  }

  function renderList() {
    const items = filtered();
    listEl.innerHTML = '';
    if (items.length === 0) {
      listEl.innerHTML = '<p class="listEmpty">没有匹配的文章。换个筛选试试？</p>';
      return;
    }
    for (const a of items) {
      const card = document.createElement('button');
      card.type = 'button';
      card.className = 'articleCard';
      card.dataset.slug = a.slug;
      if (a.slug === currentSlug) card.classList.add('active');

      const top = document.createElement('div');
      top.className = 'cardTop';
      const kind = document.createElement('span');
      kind.className = 'cardKind kind-' + (KIND_BADGE[a.kind] || 'other');
      kind.textContent = a.kindLabel ? a.kindLabel.zh : a.kind;
      top.appendChild(kind);
      const status = document.createElement('span');
      status.className = 'cardStatus status-' + a.status;
      status.textContent = a.statusLabel;
      top.appendChild(status);
      card.appendChild(top);

      const title = document.createElement('div');
      title.className = 'cardTitle';
      title.textContent = a.title;
      card.appendChild(title);

      const meta = document.createElement('div');
      meta.className = 'cardMeta';
      const bits = [];
      if (a.date) bits.push(a.date);
      if (a.cefr) bits.push(a.cefr);
      if (a.itemTotal) bits.push(`${a.itemTotal} 学习项`);
      meta.textContent = bits.join(' · ');
      card.appendChild(meta);

      card.addEventListener('click', () => openArticle(a.slug));
      listEl.appendChild(card);
    }
  }

  function openArticle(slug) {
    const a = articles.find((x) => x.slug === slug);
    if (!a) return;
    currentSlug = slug;
    listEl.querySelectorAll('.articleCard').forEach((c) =>
      c.classList.toggle('active', c.dataset.slug === slug));

    const counts = a.counts || {};
    const countBits = [
      ['words', '词'], ['phrases', '词组'], ['sentences', '句子'], ['grammar', '语法'],
    ].filter(([k]) => counts[k]).map(([k, label]) => `${counts[k]} ${label}`);

    viewEl.innerHTML =
      `<div class="viewHead">` +
        `<span class="cardKind kind-${KIND_BADGE[a.kind] || 'other'}">${a.kindLabel ? a.kindLabel.zh : a.kind}</span>` +
        `<span class="cardStatus status-${a.status}">${a.statusLabel}</span>` +
        (a.cefr ? `<span class="viewCefr">${escapeHtml(a.cefr)}</span>` : '') +
        (a.date ? `<span class="viewDate">${escapeHtml(a.date)}</span>` : '') +
      `</div>` +
      (countBits.length ? `<p class="viewCounts">📚 ${countBits.join(' · ')}</p>` : '') +
      `<div class="articleBody">${mdToHtml(a.body || '')}</div>`;

    applyZhVisibility();
    viewEl.scrollTop = 0;
    if (window.matchMedia('(max-width: 760px)').matches) {
      viewEl.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }

  // ---------- 中文 toggle ----------

  let showZh = true;
  function applyZhVisibility() {
    viewEl.querySelectorAll('[data-zh="1"]').forEach((el) => {
      el.style.display = showZh ? '' : 'none';
    });
  }

  document.getElementById('toggleZh').addEventListener('click', (e) => {
    showZh = !showZh;
    e.currentTarget.classList.toggle('active', showZh);
    applyZhVisibility();
  });

  // ---------- filters ----------

  document.querySelectorAll('.kindFilter').forEach((btn) => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.kindFilter').forEach((b) => b.classList.remove('active'));
      btn.classList.add('active');
      activeKind = btn.dataset.kind;
      renderList();
    });
  });

  const searchInput = document.getElementById('readingSearchInput');
  searchInput.addEventListener('input', () => {
    query = searchInput.value.trim().toLowerCase();
    renderList();
  });

  // ---------- init ----------

  renderList();
  if (articles.length > 0) openArticle(articles[0].slug);
})();
